<?php

			$date = date('Y-m-d');
			$time = date('H:i:s');
			
$id = $_POST['id'];
$username = $_POST['username'];
$home_computer_amt = $_POST['home_computer_amt'];
$home_computer_date = $_POST['home_computer_date'];
$home_entertain_eq_amt = $_POST['home_entertain_eq_amt'];
$home_entertain_eq_date = $_POST['home_entertain_eq_date'];
$home_no_tv_amt = $_POST['home_no_tv_amt'];
$home_no_tv_date = $_POST['home_no_tv_date'];
$home_new_energystar_fridge_amt = $_POST['home_new_energystar_fridge_amt'];
$home_new_energystar_fridge_date = $_POST['home_new_energystar_fridge_date'];
$home_fridge_maint_amt = $_POST['home_fridge_maint_amt'];
$home_fridge_maint_date = $_POST['home_fridge_maint_date'];
$home_seal_air_leaks_amt = $_POST['home_seal_air_leaks_amt'];
$home_seal_air_leaks_date = $_POST['home_seal_air_leaks_date'];
$home_new_energystar_washer_amt = $_POST['home_new_energystar_washer_amt'];
$home_new_energystar_washer_date = $_POST['home_new_energystar_washer_date'];
$home_use_clothesline_amt = $_POST['home_use_clothesline_amt'];
$home_use_clothesline_date = $_POST['home_use_clothesline_date'];
$home_clean_ac_filter_amt = $_POST['home_clean_ac_filter_amt'];
$home_clean_ac_filter_date = $_POST['home_clean_ac_filter_date'];
$home_use_no_ac_amt = $_POST['home_use_no_ac_amt'];
$home_use_no_ac_date = $_POST['home_use_no_ac_date'];
$home_dishw_energy_saving_amt = $_POST['home_dishw_energy_saving_amt'];
$home_dishw_energy_saving_date = $_POST['home_dishw_energy_saving_date'];
$home_replace_dishw_amt = $_POST['home_replace_dishw_amt'];
$home_replace_dishw_date = $_POST['home_replace_dishw_date'];
$home_ac_to_74_amt = $_POST['home_ac_to_74_amt'];
$home_ac_to_74_date = $_POST['home_ac_to_74_date'];
$home_ac_to_76_amt = $_POST['home_ac_to_76_amt'];
$home_ac_to_76_date = $_POST['home_ac_to_76_date'];
$home_push_lawnmower_amt = $_POST['home_push_lawnmower_amt'];
$home_push_lawnmower_date = $_POST['home_push_lawnmower_date'];
$home_rake_lawn_amt = $_POST['home_rake_lawn_amt'];
$home_rake_lawn_date = $_POST['home_rake_lawn_date'];
$home_replace_incand_w_cfl_var = $_POST['home_replace_incand_w_cfl_var'];
$home_replace_incand_w_cfl_amt = $_POST['home_replace_incand_w_cfl_amt'];
$home_replace_incand_w_cfl_date = $_POST['home_replace_incand_w_cfl_date'];
$home_purchase_100kW_rec_var = $_POST['home_purchase_100kW_rec_var'];
$home_purchase_100kW_rec_amt = $_POST['home_purchase_100kW_rec_amt'];
$home_purchase_100kW_rec_date = $_POST['home_purchase_100kW_rec_date'];
$home_reduce_showers_var = $_POST['home_reduce_showers_var'];
$home_reduce_showers_amt = $_POST['home_reduce_showers_amt'];
$home_reduce_showers_date = $_POST['home_reduce_showers_date'];
$home_plant_trees_var = $_POST['home_plant_trees_var'];
$home_plant_trees_amt = $_POST['home_plant_trees_amt'];
$home_plant_trees_date = $_POST['home_plant_trees_date'];
$home_wash_clothes_cold_w_amt = $_POST['home_wash_clothes_cold_w_amt'];
$home_wash_clothes_cold_w_date = $_POST['home_wash_clothes_cold_w_date'];
$home_low_flow_showerhead_amt = $_POST['home_low_flow_showerhead_amt'];
$home_low_flow_showerhead_date = $_POST['home_low_flow_showerhead_date'];
$home_hot_water_to_130_amt = $_POST['home_hot_water_to_130_amt'];
$home_hot_water_to_130_date = $_POST['home_hot_water_to_130_date'];
$home_hot_water_to_120_amt = $_POST['home_hot_water_to_120_amt'];
$home_hot_water_to_120_date = $_POST['home_hot_water_to_120_date'];
$home_thermostat_to_68_amt = $_POST['home_thermostat_to_68_amt'];
$home_thermostat_to_68_date = $_POST['home_thermostat_to_68_date'];
$home_thermostat_to_66_amt = $_POST['home_thermostat_to_66_amt'];
$home_thermostat_to_66_date = $_POST['home_thermostat_to_66_date'];
$home_wrap_water_heater_date = $_POST['home_wrap_water_heater_date'];
$home_wrap_water_heater_amt = $_POST['home_wrap_water_heater_amt'];
$home_weatherstrip_amt = $_POST['home_weatherstrip_amt'];
$home_weatherstrip_date = $_POST['home_weatherstrip_date'];
$home_insultate_attic_amt = $_POST['home_insultate_attic_amt'];
$home_insultate_attic_date = $_POST['home_insultate_attic_date'];
$waste_reuse_plastic_bags_var = $_POST['waste_reuse_plastic_bags_var'];
$waste_reuse_plastic_bags_amt = $_POST['waste_reuse_plastic_bags_amt'];
$waste_reuse_plastic_bags_date = $_POST['waste_reuse_plastic_bags_date'];
$waste_reuse_plastic_bottles_var = $_POST['waste_reuse_plastic_bottles_var'];
$waste_reuse_plastic_bottles_amt = $_POST['waste_reuse_plastic_bottles_amt'];
$waste_reuse_plastic_bottles_date = $_POST['waste_reuse_plastic_bottles_date'];
$waste_reuse_alum_cans_var = $_POST['waste_reuse_alum_cans_var'];
$waste_reuse_alum_cans_amt = $_POST['waste_reuse_alum_cans_amt'];
$waste_reuse_alum_cans_date = $_POST['waste_reuse_alum_cans_date'];
$waste_reuse_glass_bottles_var = $_POST['waste_reuse_glass_bottles_var'];
$waste_reuse_glass_bottles_amt = $_POST['waste_reuse_glass_bottles_amt'];
$waste_reuse_glass_bottles_date = $_POST['waste_reuse_glass_bottles_date'];
$waste_recycle_paper_var = $_POST['waste_recycle_paper_var'];
$waste_recycle_paper_amt = $_POST['waste_recycle_paper_amt'];
$waste_recycle_paper_date = $_POST['waste_recycle_paper_date'];
$waste_bring_own_bags_amt = $_POST['waste_bring_own_bags_amt'];
$waste_bring_own_bags_date = $_POST['waste_bring_own_bags_date'];
$waste_get_off_junk_mail_amt = $_POST['waste_get_off_junk_mail_amt'];
$waste_get_off_junk_mail_date = $_POST['waste_get_off_junk_mail_date'];
$trans_carpool_var = $_POST['trans_carpool_var'];
$trans_carpool_amt = $_POST['trans_carpool_amt'];
$trans_carpool_date = $_POST['trans_carpool_date'];
$trans_fly_less_miles_var = $_POST['trans_fly_less_miles_var'];
$trans_fly_less_miles_amt = $_POST['trans_fly_less_miles_amt'];
$trans_fly_less_miles_date = $_POST['trans_fly_less_miles_date'];
$trans_better_mpg_car_var = $_POST['trans_better_mpg_car_var'];
$trans_better_mpg_car_amt = $_POST['trans_better_mpg_car_amt'];
$trans_better_mpg_car_date = $_POST['trans_better_mpg_car_date'];
$trans_drive_less_miles_var = $_POST['trans_drive_less_miles_var'];
$tmp = $trans_drive_less_miles_var / 1248;
$trans_drive_less_miles_date = $_POST['trans_drive_less_miles_date'];
$trans_train_instead_of_flight_amt = $_POST['trans_train_instead_of_flight_amt'];
$trans_train_instead_of_flight_date = $_POST['trans_train_instead_of_flight_date'];
$trans_tun_up_car_amt = $_POST['trans_tun_up_car_amt'];
$trans_tun_up_car_date = $_POST['trans_tun_up_car_date'];
$trans_car_adeq_tire_press_amt = $_POST['trans_car_adeq_tire_press_amt'];
$trans_car_adeq_tire_press_date = $_POST['trans_car_adeq_tire_press_date'];
$trans_car_max_tire_press_amt = $_POST['trans_car_max_tire_press_amt'];
$trans_car_max_tire_press_date = $_POST['trans_car_max_tire_press_date'];
$food_replace_red_meat_var = $_POST['food_replace_red_meat_var'];
$food_replace_red_meat_amt = $_POST['food_replace_red_meat_amt'];
$food_replace_red_meat_date = $_POST['food_replace_red_meat_date'];
$food_meat_to_vegetarian_var = $_POST['food_meat_to_vegetarian_var'];
$food_meat_to_vegetarian_amt = $_POST['food_meat_to_vegetarian_amt'];
$food_meat_to_vegetarian_date = $_POST['food_meat_to_vegetarian_date'];
$food_vegetarian_to_organic_var = $_POST['food_vegetarian_to_organic_var'];
$food_vegetarian_to_organic_amt = $_POST['food_vegetarian_to_organic_amt'];
$food_vegetarian_to_organic_date = $_POST['food_vegetarian_to_organic_date'];
$food_vegetarian_to_vegan_var = $_POST['food_vegetarian_to_vegan_var'];
$food_vegetarian_to_vegan_amt = $_POST['food_vegetarian_to_vegan_amt'];
$food_vegetarian_to_vegan_date = $_POST['food_vegetarian_to_vegan_date'];
$food_vegan_to_organic_var = $_POST['food_vegan_to_organic_var'];
$food_vegan_to_organic_amt = $_POST['food_vegan_to_organic_amt'];
$food_vegan_to_organic_date = $_POST['food_vegan_to_organic_date'];
$reduct1_total = $home_computer_amt+$home_entertain_eq_amt+$home_no_tv_amt+$home_new_energystar_fridge_amt+$home_fridge_maint_amt+$home_seal_air_leaks_amt+$home_new_energystar_washer_amt+$home_use_clothesline_amt+$home_clean_ac_filter_amt+$home_use_no_ac_amt+$home_dishw_energy_saving_amt+$home_replace_dishw_amt+$home_ac_to_74_amt+$home_ac_to_76_amt+$home_push_lawnmower_amt+$home_rake_lawn_amt+$home_replace_incand_w_cfl_amt+$home_purchase_100kW_rec_amt+$home_reduce_showers_amt+$home_plant_trees_amt+$home_wash_clothes_cold_w_amt+$home_low_flow_showerhead_amt+$home_hot_water_to_130_amt+$home_hot_water_to_120_amt+$home_thermostat_to_68_amt+$home_thermostat_to_66_amt+$home_wrap_water_heater_amt+$home_weatherstrip_amt+$home_insultate_attic_amt+$waste_reuse_plastic_bags_amt+$waste_reuse_plastic_bottles_amt+$waste_reuse_alum_cans_amt+$waste_reuse_glass_bottles_amt+$waste_recycle_paper_amt+$waste_bring_own_bags_amt+$waste_get_off_junk_mail_amt+$trans_carpool_amt+$trans_fly_less_miles_amt+$trans_better_mpg_car_amt+$trans_drive_less_miles_var+$trans_train_instead_of_flight_amt+$trans_tun_up_car_amt+$trans_car_adeq_tire_press_amt+$trans_car_max_tire_press_amt+$food_replace_red_meat_amt+$food_meat_to_vegetarian_amt+$food_vegetarian_to_organic_amt+$food_vegetarian_to_vegan_amt+$food_vegan_to_organic_amt;
$metric_data = 0;
			
include('../connect-db.php');	

		
			mysql_query("INSERT INTO `shantiom_sandbeta`.`user_reduc_calc1` (`id`, `username`, `home_computer_amt`, `home_computer_date`, `home_entertain_eq_amt`, `home_entertain_eq_date`, `home_no_tv_amt`, `home_no_tv_date`, `home_new_energystar_fridge_amt`, `home_new_energystar_fridge_date`, `home_fridge_maint_amt`, `home_fridge_maint_date`, `home_seal_air_leaks_amt`, `home_seal_air_leaks_date`, `home_new_energystar_washer_amt`, `home_new_energystar_washer_date`, `home_use_clothesline_amt`, `home_use_clothesline_date`, `home_clean_ac_filter_amt`, `home_clean_ac_filter_date`, `home_use_no_ac_amt`, `home_use_no_ac_date`, `home_dishw_energy_saving_amt`, `home_dishw_energy_saving_date`, `home_replace_dishw_amt`, `home_replace_dishw_date`, `home_ac_to_74_amt`, `home_ac_to_74_date`, `home_ac_to_76_amt`, `home_ac_to_76_date`, `home_push_lawnmower_amt`, `home_push_lawnmower_date`, `home_rake_lawn_amt`, `home_rake_lawn_date`, `home_replace_incand_w_cfl_var`, `home_replace_incand_w_cfl_amt`, `home_replace_incand_w_cfl_date`, `home_purchase_100kW_rec_var`, `home_purchase_100kW_rec_amt`, `home_purchase_100kW_rec_date`, `home_reduce_showers_var`, `home_reduce_showers_amt`, `home_reduce_showers_date`, `home_plant_trees_var`, `home_plant_trees_amt`, `home_plant_trees_date`, `home_wash_clothes_cold_w_amt`, `home_wash_clothes_cold_w_date`, `home_low_flow_showerhead_amt`, `home_low_flow_showerhead_date`, `home_hot_water_to_130_amt`, `home_hot_water_to_130_date`, `home_hot_water_to_120_amt`, `home_hot_water_to_120_date`, `home_thermostat_to_68_amt`, `home_thermostat_to_68_date`, `home_thermostat_to_66_amt`, `home_thermostat_to_66_date`, `home_wrap_water_heater_amt`, `home_wrap_water_heater_date`, `home_weatherstrip_amt`, `home_weatherstrip_date`, `home_insultate_attic_amt`, `home_insultate_attic_date`, `waste_reuse_plastic_bags_var`, `waste_reuse_plastic_bags_amt`, `waste_reuse_plastic_bags_date`, `waste_reuse_plastic_bottles_var`, `waste_reuse_plastic_bottles_amt`, `waste_reuse_plastic_bottles_date`, `waste_reuse_alum_cans_var`, `waste_reuse_alum_cans_amt`, `waste_reuse_alum_cans_date`, `waste_reuse_glass_bottles_var`, `waste_reuse_glass_bottles_amt`, `waste_reuse_glass_bottles_date`, `waste_recycle_paper_var`, `waste_recycle_paper_amt`, `waste_recycle_paper_date`, `waste_bring_own_bags_amt`, `waste_bring_own_bags_date`, `waste_get_off_junk_mail_amt`, `waste_get_off_junk_mail_date`, `trans_carpool_var`, `trans_carpool_amt`, `trans_carpool_date`, `trans_fly_less_miles_var`, `trans_fly_less_miles_amt`, `trans_fly_less_miles_date`, `trans_better_mpg_car_var`, `trans_better_mpg_car_amt`, `trans_better_mpg_car_date`, `trans_drive_less_miles_var`, `trans_drive_less_miles_amt`, `trans_drive_less_miles_date`, `trans_train_instead_of_flight_amt`, `trans_train_instead_of_flight_date`, `trans_tun_up_car_amt`, `trans_tun_up_car_date`, `trans_car_adeq_tire_press_amt`, `trans_car_adeq_tire_press_date`, `trans_car_max_tire_press_amt`, `trans_car_max_tire_press_date`, `food_replace_red_meat_var`, `food_replace_red_meat_amt`, `food_replace_red_meat_date`, `food_meat_to_vegetarian_var`, `food_meat_to_vegetarian_amt`, `food_meat_to_vegetarian_date`, `food_vegetarian_to_organic_var`, `food_vegetarian_to_organic_amt`, `food_vegetarian_to_organic_date`, `food_vegetarian_to_vegan_var`, `food_vegetarian_to_vegan_amt`, `food_vegetarian_to_vegan_date`, `food_vegan_to_organic_var`, `food_vegan_to_organic_amt`, `food_vegan_to_organic_date`, `reduct1_total`,`metric_data`) VALUES (NULL, '$username', '$home_computer_amt', '$home_computer_date', '$home_entertain_eq_amt', '$home_entertain_eq_date', '$home_no_tv_amt', '$home_no_tv_date', '$home_new_energystar_fridge_amt', '$home_new_energystar_fridge_date', '$home_fridge_maint_amt', '$home_fridge_maint_date', '$home_seal_air_leaks_amt', '$home_seal_air_leaks_date', '$home_new_energystar_washer_amt', '$home_new_energystar_washer_date', '$home_use_clothesline_amt', '$home_use_clothesline_date', '$home_clean_ac_filter_amt', '$home_clean_ac_filter_date', '$home_use_no_ac_amt', '$home_use_no_ac_date', '$home_dishw_energy_saving_amt', '$home_dishw_energy_saving_date', '$home_replace_dishw_amt', '$home_replace_dishw_date', '$home_ac_to_74_amt', '$home_ac_to_74_date', '$home_ac_to_76_amt', '$home_ac_to_76_date', '$home_push_lawnmower_amt', '$home_push_lawnmower_date', '$home_rake_lawn_amt', '$home_rake_lawn_date', '$home_replace_incand_w_cfl_var', '$home_replace_incand_w_cfl_amt', '$home_replace_incand_w_cfl_date', '$home_purchase_100kW_rec_var', '$home_purchase_100kW_rec_amt', '$home_purchase_100kW_rec_date', '$home_reduce_showers_var', '$home_reduce_showers_amt', '$home_reduce_showers_date', '$home_plant_trees_var', '$home_plant_trees_amt', '$home_plant_trees_date', '$home_wash_clothes_cold_w_amt', '$home_wash_clothes_cold_w_date', '$home_low_flow_showerhead_amt', '$home_low_flow_showerhead_date', '$home_hot_water_to_130_amt', '$home_hot_water_to_130_date', '$home_hot_water_to_120_amt', '$home_hot_water_to_120_date', '$home_thermostat_to_68_amt', '$home_thermostat_to_68_date', '$home_thermostat_to_66_amt', '$home_thermostat_to_66_date', '$home_wrap_water_heater_amt', '$home_wrap_water_heater_date', '$home_weatherstrip_amt', '$home_weatherstrip_date', '$home_insultate_attic_amt', '$home_insultate_attic_date', '$waste_reuse_plastic_bags_var', '$waste_reuse_plastic_bags_amt', '$waste_reuse_plastic_bags_date', '$waste_reuse_plastic_bottles_var', '$waste_reuse_plastic_bottles_amt', '$waste_reuse_plastic_bottles_date', '$waste_reuse_alum_cans_var', '$waste_reuse_alum_cans_amt', '$waste_reuse_alum_cans_date', '$waste_reuse_glass_bottles_var', '$waste_reuse_glass_bottles_amt', '$waste_reuse_glass_bottles_date', '$waste_recycle_paper_var', '$waste_recycle_paper_amt', '$waste_recycle_paper_date', '$waste_bring_own_bags_amt', '$waste_bring_own_bags_date', '$waste_get_off_junk_mail_amt', '$waste_get_off_junk_mail_date', '$trans_carpool_var', '$trans_carpool_amt', '$trans_carpool_date', '$trans_fly_less_miles_var', '$trans_fly_less_miles_amt', '$trans_fly_less_miles_date', '$trans_better_mpg_car_var', '$trans_better_mpg_car_amt', '$trans_better_mpg_car_date', '$tmp', '$trans_drive_less_miles_var', '$trans_drive_less_miles_date', '$trans_train_instead_of_flight_amt', '$trans_train_instead_of_flight_date', '$trans_tun_up_car_amt', '$trans_tun_up_car_date', '$trans_car_adeq_tire_press_amt', '$trans_car_adeq_tire_press_date', '$trans_car_max_tire_press_amt', '$trans_car_max_tire_press_date', '$food_replace_red_meat_var', '$food_replace_red_meat_amt', '$food_replace_red_meat_date', '$food_meat_to_vegetarian_var', '$food_meat_to_vegetarian_amt', '$food_meat_to_vegetarian_date', '$food_vegetarian_to_organic_var', '$food_vegetarian_to_organic_amt', '$food_vegetarian_to_organic_date', '$food_vegetarian_to_vegan_var', '$food_vegetarian_to_vegan_amt', '$food_vegetarian_to_vegan_date', '$food_vegan_to_organic_var', '$food_vegan_to_organic_amt', '$food_vegan_to_organic_date', '$reduct1_total','$metric_data');") or die(mysql_error()); 
									
				
					 header("Location: http://beta.earthdeeds.com/mystuff.php");  


?>